### ISSUE TITLE
Unable to Logout

### ISSUE THREAD

**Issue by LuzzHub** [AlgoWorldNFT/algoworld-swapper#164]
I had a login on the swapper via MyAlgo. I have been trying to logout, but no luck. The swapper still keeps me logged in, even after refreshing. Interestingly, the "active account" dropdown on my account doesn't show my wallet and it's empty. See attached screenshot.
Browser is Brave 1.50.121 for Mac (intel)
![Screenshot 2023-05-03 at 10 36 48 AM](https://user-images.githubusercontent.com/118074218/235868580-cb9de377-ea1c-4f7a-b4db-3cdd432c9250.png)

**Comment by aorumbayev** [comment]
You need to clear webpage cache and local storage as my Algo stores auth session in local storage. 

Please find below a step-by-step guide on how to clear webpage cache, cookies, and local storage for popular web browsers:

1. Google Chrome:
   a. Click on the three-dot menu icon in the top-right corner of the browser.
   b. Hover over "More tools" and click on "Clear browsing data."
   c. In the "Clear browsing data" window, select "Cookies and other site data" and "Cached images and files."
   d. Optionally, choose "All time" from the "Time range" dropdown menu to clear all cache and cookies.
   e. Click on "Clear data."

2. Mozilla Firefox:
   a. Click on the three-line menu icon in the top-right corner of the browser.
   b. Click on "Options."
   c. Select "Privacy & Security" from the left-hand side menu.
   d. Scroll down to the "Cookies and Site Data" section, and click on "Clear Data."
   e. Make sure both "Cookies and Site Data" and "Cached Web Content" are checked.
   f. Click on "Clear."

3. Microsoft Edge:
   a. Click on the three-dot menu icon in the top-right corner of the browser.
   b. Click on "Settings."
   c. Select "Privacy, search, and services" from the left-hand side menu.
   d. Under the "Clear browsing data" section, click on "Choose what to clear."
   e. Select "Cookies and other site data" and "Cached images and files."
   f. Optionally, choose "All time" from the "Time range" dropdown menu to clear all cache and cookies.
   g. Click on "Clear now."

4. Safari (macOS):
   a. Click on "Safari" in the top-left corner of the screen, and select "Preferences."
   b. Click on the "Privacy" tab.
   c. Click on "Manage Website Data."
   d. To clear all cache and cookies, click on "Remove All." To clear data for specific sites, select the site(s) and click on "Remove."
   e. Click on "Done."

Let me know if you have any questions or need assistance with a different browser. 

Otherwise I was able to replicate the issue and clearing local storage and cache works. Hence resolving for now.
